In [1]:
list1=[x for x in range(1,11)]
print(list1)
import numpy as np
data1=np.array(list1)
print(data1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
data2=np.linspace(0,1,20)
print(data2)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [7]:
import numpy as np
data3=np.random.randint(1,100,10)
print(data3) 


[12 61 20 64 55  4 54 60 88 42]


In [10]:
import numpy as np
data1_2d=np.zeros((3,4))
print(data1_2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
data2_2d=np.random.rand(5,5)
print(data2_2d)

[[0.94755079 0.99767634 0.77692365 0.65656106 0.88316928]
 [0.17439097 0.26555891 0.3645512  0.40958818 0.48997455]
 [0.96716266 0.81424983 0.03014505 0.40035983 0.92845767]
 [0.98737245 0.78606136 0.50199968 0.39192354 0.21266559]
 [0.16741235 0.83313302 0.67157857 0.13613639 0.98245657]]


In [20]:
import numpy as np
data3_2d=np.eye(2,2)
print(data3_2d)

[[1. 0.]
 [0. 1.]]


In [22]:
import numpy as np
data1_3d=np.zeros((3,4,2))
print(data1_3d)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [23]:
data2_3d=np.random.randint(1,100,(2,3,3))
print(data2_3d)

[[[43  1  8]
  [21 78 36]
  [ 5 83 95]]

 [[44 11 87]
  [18 76 76]
  [12  8 69]]]


In [32]:
data3_3d=np.arange(1,25).reshape(2,3,4)
print(data3_3d)
mean=data3_3d.mean()
print(mean)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
12.5


In [29]:
row_means=np.mean(data3_3d,axis=1)
print(row_means)

[[ 5.  6.  7.  8.]
 [17. 18. 19. 20.]]


In [37]:
column_means=np.mean(data3_3d,axis=2)
print(column_means)

[[ 2.5  6.5 10.5]
 [14.5 18.5 22.5]]


In [39]:
row=[]
for matrix in data3_3d:
    for rows in matrix:
        mean=rows.mean()
        row.append(float(mean))

print(row)

[2.5, 6.5, 10.5, 14.5, 18.5, 22.5]
